//
//  HomeViewPresenter.swift
//  TextAnalyzer
//
//  Created by Francis Breidenbach on 12/18/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol HomeViewPresentationLogic {
  func presentAnalysis(response: HomeView.AnalyzeText.Response)
}

class HomeViewPresenter: HomeViewPresentationLogic {
  weak var viewController: HomeViewDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: HomeView.AnalyzeText.Response) {
////    let viewModel = HomeView.AnalyzeText.ViewModel()
////    viewController?.displaySomething(viewModel: viewModel)
//  }
  
  func presentAnalysis(response: HomeView.AnalyzeText.Response) {
    let viewModel = HomeView.AnalyzeText.ViewModel(analysis: response.analysis)
    viewController?.displayAnalysis(viewModel: viewModel)
  }
  
}
