//
//  ShowAnalysisInteractor.swift
//  TextAnalyzer
//
//  Created by Francis Breidenbach on 12/19/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowAnalysisBusinessLogic {
  func showProcessedAnalysis(request: ShowAnalysis.Something.Request)
}

protocol ShowAnalysisDataStore {
  var analysis: Analysis? { get set }
}

class ShowAnalysisInteractor: ShowAnalysisBusinessLogic, ShowAnalysisDataStore {
  var presenter: ShowAnalysisPresentationLogic?
  var analysis: Analysis?
  
  // MARK: Do something
  
  func showProcessedAnalysis(request: ShowAnalysis.Something.Request) {
    guard let storedAnalysis = analysis else { return }
    
    let response = ShowAnalysis.Something.Response(analysis: storedAnalysis)
    presenter?.presentAnalysis(response: response)
  }
}
