//
//  ShowAnalysisRouter.swift
//  TextAnalyzer
//
//  Created by Francis Breidenbach on 12/19/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ShowAnalysisRoutingLogic {
  //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ShowAnalysisDataPassing {
  var dataStore: ShowAnalysisDataStore? { get }
}

class ShowAnalysisRouter: NSObject, ShowAnalysisRoutingLogic, ShowAnalysisDataPassing {
  weak var viewController: ShowAnalysisViewController?
  var dataStore: ShowAnalysisDataStore?
  
  // MARK: Routing
  
  //func routeToSomewhere(segue: UIStoryboardSegue?)
  //{
  //  if let segue = segue {
  //    let destinationVC = segue.destination as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //  } else {
  //    let storyboard = UIStoryboard(name: "Main", bundle: nil)
  //    let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
  //    var destinationDS = destinationVC.router!.dataStore!
  //    passDataToSomewhere(source: dataStore!, destination: &destinationDS)
  //    navigateToSomewhere(source: viewController!, destination: destinationVC)
  //  }
  //}

  // MARK: Navigation
  
  //func navigateToSomewhere(source: ShowAnalysisViewController, destination: SomewhereViewController)
  //{
  //  source.show(destination, sender: nil)
  //}
  
  // MARK: Passing data
  
  //func passDataToSomewhere(source: ShowAnalysisDataStore, destination: inout SomewhereDataStore)
  //{
  //  destination.name = source.name
  //}
}
