//
//  ShowAnalysisPresenter.swift
//  TextAnalyzer
//
//  Created by Francis Breidenbach on 12/19/17.
//  Copyright (c) 2017 Francis Breidenbach. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ShowAnalysisPresentationLogic {
  func presentAnalysis(response: ShowAnalysis.Something.Response)
}

class ShowAnalysisPresenter: ShowAnalysisPresentationLogic {
  weak var viewController: ShowAnalysisDisplayLogic?
  
  // MARK: Do something
  
  func presentAnalysis(response: ShowAnalysis.Something.Response) {
    let viewModel = ShowAnalysis.Something.ViewModel(analysis: response.analysis)
    viewController?.displayAnalysis(viewModel: viewModel)
  }
}
